// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIqeedYe8YqjRDRrOW4srGMdYVqIuafaY',
    appId: '1:907756919405:android:69dfeabd0957555b92fd64',
    messagingSenderId: '907756919405',
    projectId: 'vandad-insta-clone',
    storageBucket: 'vandad-insta-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBefHyPaVPrZytptXwnRo_-ocKR4pdJ0PA',
    appId: '1:907756919405:ios:0a3eabbe96b290df92fd64',
    messagingSenderId: '907756919405',
    projectId: 'vandad-insta-clone',
    storageBucket: 'vandad-insta-clone.appspot.com',
    androidClientId: '907756919405-b7lsqh5bq7peisi48m7hglq7jcotcl4d.apps.googleusercontent.com',
    iosClientId: '907756919405-o9rc1a3mrabvo79vt9dv02u38ve85oim.apps.googleusercontent.com',
    iosBundleId: 'com.example.instantGram',
  );
}
